config/routes.rb
Rails.application.routes.draw do
  


  resources :auctions do
  	resources :tickets, except: [:index], controller: 'auctions/tickets'
	end
  devise_for :users

  get '/users/:id' => 'users#show', :as => :user

  root 'auctions#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/auction.rb
class Auction < ApplicationRecord
	belongs_to :user
	has_many :tickets
	validates :title, :presence => true
	validates :price, :presence => true
	validates_length_of :title, maximum: 20, minimum: 2
	
end

app/controllers/auctions/tickets_controller.rb
class Auctions::TicketsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :set_auction
  before_action :go_back, only: [:new, :create]
  before_action :set_top_ticket

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @auction = Auction.find(params[:auction_id])
    @ticket.user_id = current_user.id
    @ticket.auction_id = @auction.id
    if @ticket.amount != nil
      if @auction.ends_at > DateTime.now
        if @top_ticket == nil
          if @ticket.amount < @auction.price
            redirect_to request.referrer, notice: 'Minimal price is higher'
          else
            respond_to do |format|
              if @ticket.save
                format.html { redirect_to auction_url(@ticket.auction_id), notice: 'Ticket was successfully created.' }
                format.json { render :show, status: :created, location: @ticket }
              else
                format.html { render :new }
                format.json { render json: @ticket.errors, status: :unprocessable_entity }
              end
            end  
          end
        else
          if @ticket.amount <= @top_ticket.amount
             redirect_to request.referrer, notice: 'Current pirce is higher'
          else
            respond_to do |format|
              if @ticket.save
                format.html { redirect_to auction_url(@ticket.auction_id), notice: 'Ticket was successfully created.' }
                format.json { render :show, status: :created, location: @ticket }
              else
                format.html { render :new }
                format.json { render json: @ticket.errors, status: :unprocessable_entity }
              end
            end
          end
        end
      else
        redirect_to request.referrer, notice: 'Time left for bidding is over'
      end
    else
      redirect_to request.referrer, notice: 'Cant be null'
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to auction_url(@ticket.auction_id), notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    def set_auction
      @auction = Auction.find(params[:auction_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:amount)
    end

    def go_back
      if @auction.user_id == current_user.id
        respond_to do |format|
          format.html { redirect_to @auction, notice: 'Cant bid your own auction.' }
        end
      end
    end

    def set_top_ticket
      @top_ticket = Ticket.where(:auction_id => @auction.id).order('amount DESC').first
    end

end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :show]
  before_action :set_auction, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /auctions
  # GET /auctions.json
  def index
    @auctions = Auction.where(:active_boolean => 1).
                        where('ends_at > ?', DateTime.now).
                        paginate(page: params[:page], per_page: 10)
    #@auctions = Auction.where(:active_boolean => true).
    #                    where("ends_at > ?", DateTime.now).
    #                    paginate(page: params[:page], per_page: 10)
    @search = params["search"]
    if @search.present?
      @title = @search["title"]
      @auctions = Auction.where("title LIKE ?", "%#{@title}%").
                          where(:active_boolean => 1).where('ends_at > ?', DateTime.now).
                          paginate(page: params[:page], per_page: 10)
    end

  #  if user_signed_in?
  #    @auctions = Auction.where.not(:user_id => current_user.id) . paginate(page: params[:page], per_page: 5)
  #  else 
  #    @auctions = Auction.all.paginate(page: params[:page], per_page: 5)
  #  end
  end

  # GET /auctions/1
  # GET /auctions/1.json
  def show
    @tickets = Ticket.where(:auction_id => @auction.id).order('amount DESC')
  end

  # GET /auctions/new
  def new
    @auction = Auction.new

  end

  # GET /auctions/1/edit
  def edit
    if !current_user.admin?
      redirect_to @auction
    end
  #  if !current_user.try(:admin?) 
   #   redirect_to auctions_path
   # end
  end

  # POST /auctions
  # POST /auctions.json
  def create
    @auction = Auction.new(auction_params)
    @auction.user_id = current_user.id
    @auction.active_boolean = true
    respond_to do |format|
      if @auction.save
        format.html { redirect_to @auction, notice: 'Auction was successfully created.' }
        format.json { render :show, status: :created, location: @auction }
      else
        format.html { render :new }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auctions/1
  # PATCH/PUT /auctions/1.json
  def update
    @auction.ends_at = DateTime.now
    respond_to do |format|
      if @auction.update(auction_params)
        format.html { redirect_to @auction, notice: 'Auction was successfully updated.' }
        format.json { render :show, status: :ok, location: @auction }
      else
        format.html { render :edit }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1
  # DELETE /auctions/1.json
  def destroy
    if current_user.admin?
      @auction.destroy
      respond_to do |format|
        format.html { redirect_to auctions_url, notice: 'Auction was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auction
      @auction = Auction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auction_params
      params.require(:auction).permit(:description, :price, :title, :ends_at, :active_boolean)
    end

    def set_user
      @user = User.where(:id => @auction.user_id)
    end
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/auctions/_form.html.erb
<%= simple_form_for @auction, :html => {:mutlipart=> true} do |f| %>
<%= f.input :title,required: true%>
<%= f.input :description,required: true%>
<%= f.input :price%>
<%= f.datetime_select(:ends_at, required: true) %>
</br>
</br>

<%= f.button :submit, required: true, :class=> 'btn btn-primary'%>
<%end%>

app/views/auctions/edit.html.erb
<h1>Editing Auction</h1>

<%= render 'form', auction: @auction %>

<%= link_to 'Show', @auction %> |
<%= link_to 'Back', auctions_path %>

app/views/auctions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Auctions</h1>

<%= simple_form_for :search, url: auctions_path, method: "GET", html: { class: 'form-inline' } do |f| %>
  <%= f.input :title, required: true, input_html: {value: ""} %>   
  <%= f.submit "Search", class: "btn btn-primary" %>
<% end %>



<table class="table" width="100%" style="word-break:break-all;">
  <thead>
    <tr>
      <th width="15%">Title</th>
      <th width="30%">Description</th>
      <th width="10%">Price</th>
      <th width="25%">Time left</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auctions.each do |auction| %>
  <% if current_user.present? %>
  	<% if auction.user_id == current_user.id %>
  	   <tr bgcolor="#66ffcc">
  	<%else%>
       <tr>
  	<%end%>
  <%end%>
        <td width="20%"><%= auction.title %></td>
        <% if auction.description.length > 40 %>
          <td width="20%"><%= auction.description[0,40] %>...</td>
        <%else%>
          <td width="20%"><%= auction.description%></td>
          <%end%>
        <td width="10%"><%= auction.price %> zł</td>
        <td width="5%"><%= TimeDifference.between(DateTime.now, auction.ends_at).humanize %></td>
        <div class=btn-group>
          <td><%= button_to 'Show', auction, :method => :get, :class => 'btn btn-primary' %></td>

          <% if current_user.present? %>
            <% if current_user.admin? %>
              <td><%= button_to 'Edit', edit_auction_path(auction), :method => :get, :class => 'btn btn-primary' %></td>
              <td><%= link_to 'Edit', edit_auction_path(auction) %></td>
              <td><%= link_to 'Destroy', auction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <%end%>
          <%end%>
        </div>
      </tr>
      <% end %>  
  </tbody>
</table>
<br>

<%= button_to "New Auction", new_auction_path, :method => :get, :class=> 'btn btn-primary' %>
<center> <%= will_paginate @auctions%> </center>

app/views/auctions/new.html.erb
<h1>New Auction</h1>

<%= render 'form' %>

app/views/auctions/show.html.erb
<% if @auction.active_boolean || @auction.ends_at < DateTime.now %>
  <div class="success">
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
    <strong><center>STATUS active</center></strong>
  </div>
  <%else%>
  <div class="alert">
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
    <strong><center>STATUS inactive</center></strong>
  </div>
<% end %>

<p>
  <strong>Description</strong>
  <br/>
  <div class="disc">
    <%= h(@auction.description).gsub(/\n/, '<br/>').html_safe %>
  </div>
</p>

<p>
  <strong>Start bid</strong>
  <%= @auction.price %>
</p>
<p>
  <strong>User</strong>
  <% @user.each do |user| %>
  <%= link_to user.email ,user %>
  <% end %>
</p>
<p>
    <strong>Time left</strong>
    <%= TimeDifference.between(DateTime.now, @auction.ends_at).humanize %>
  </p>
<table class="table table-striped table-dark">
  <tbody class="table table-striped table-dark">
  <p>
  	<strong>Current price</strong>
  	<% @tickets.each do |ticket|  %>
  	<tr>
          <td><%= ticket.amount %></td>
  	</tr>
  	<% end %>
  </p>
  </tbody>
</table>
<% if current_user.try(:admin) %>
  <%= link_to 'Edit', edit_auction_path(@auction) %> |
<% end %> 
<div class=btn-group>
  <%= button_to 'Back', auctions_path, :method => :get, :class=> 'btn btn-primary' %>
  <%= button_to "Bid", new_auction_ticket_path(@auction), :method => :get, :class=> 'btn btn-primary' %>
</div>


<p id="notice"><%= notice %></p>